# Site settings
title: zhaoxiaozhou blog 
email: 
description: "blog of learning process"
baseurl: ""
url: "https://zhaoxiaozhou.github.io/"
github_username: zhaoxiaozhou

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
